services:
#  oos-api:
#    build: .
#    ports:
#      - "443:443"
  oos-db:
    image: mysql:8.0.27
    container_name: oos-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: oosdb
      MYSQL_USER: oos_dbuser
      MYSQL_PASSWORD: passw0rd
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
      - oos-db-volume:/var/lib/mysql
      - ./config:/etc/mysql/conf.d
volumes:
  oos-db-volume: null