version: '3'

services:
  api:
    build: .
    image: oos-api:latest
    container_name: oos-api
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      SYSTEM_USER: system@oos
      SYSTEM_PASSWORD: aA123456
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/oosdb?useUnicode=true&characterEncoding=UTF-8&useLegacyDatetimeCode=false
    depends_on:
      - db
    networks:
      - backend

  db:
    image: mysql:8.0.27
    container_name: oos-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: oosdb
      MYSQL_USER: oos_dbuser
      MYSQL_PASSWORD: passw0rd
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
      - oos-db-volume:/var/lib/mysql
      - ./config:/etc/mysql/conf.d
    networks:
      - backend

volumes:
  oos-db-volume:

networks:
  backend:
